lib/demo_web/router.ex
defmodule DemoWeb.Router do
  use DemoWeb, :router

  import Utilities, only: [nilify_error: 1]

  alias Guardian.Plug.LoadResource, as: Guardian_LoadResource
  alias Guardian.Plug.Pipeline, as: Guardian_Pipeline
  alias Guardian.Plug.VerifyHeader, as: Guardian_VerifyHeader
  alias Guardian.Plug.VerifySession, as: Guardian_VerifySession
  alias DemoWeb.Guardian
  alias DemoWeb.AuthErrorHandler
  alias DemoWeb.GuardianController

  pipeline :browser do
    plug :accepts, ["html"]
    plug ProperCase.Plug.SnakeCaseParams
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian_Pipeline, module: Guardian, error_handler: AuthErrorHandler
    plug Guardian_VerifySession
    plug :authenticate_agent
  end

  scope "/", DemoWeb.Browser do
    pipe_through :browser

    get "/", PageController, :index

    resources "/administrators", AdministratorController, except: [:edit, :update]
    resources "/couriers",       CourierController,       except: [:edit, :update]
    resources "/orders",         OrderController
    resources "/patients",       PatientController,       except: [:edit, :update]
    resources "/pharmacies",     PharmacyController,      except: [:edit, :update]

    get "/orders.csv", OrderController, :csv_index

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  pipeline :api do
    plug :accepts, ["json", "csv"]
    plug ProperCase.Plug.SnakeCaseParams
    plug Guardian_Pipeline,
      error_handler: DemoWeb.Api.SessionController,
      module: DemoWeb.Guardian
    plug Guardian_VerifyHeader, realm: "Token"
    plug Guardian_LoadResource, allow_blank: true
  end

  scope "/api", DemoWeb.Api, as: :api do
    pipe_through :api

    post   "/login",              SessionController,       :create

    get    "/administrators",     AdministratorController, :index
    get    "/administrators/:id", AdministratorController, :show
    post   "/administrators",     AdministratorController, :create

    get    "/couriers",           CourierController,       :index
    get    "/couriers/:id",       CourierController,       :show
    post   "/couriers",           CourierController,       :create

    delete "/orders/:id",         OrderController,         :cancel
    get    "/orders",             OrderController,         :index
    get    "/orders/:id",         OrderController,         :show
    post   "/orders",             OrderController,         :create
    post   "/orders/:id/cancel",  OrderController,         :cancel
    post   "/orders/:id/deliver", OrderController,         :deliver
    post   "/orders/:id/mark_undeliverable", OrderController, :mark_undeliverable

    get    "/patients",           PatientController,       :index
    get    "/patients/:id",       PatientController,       :show
    post   "/patients",           PatientController,       :create

    get    "/pharmacies",         PharmacyController,      :index
    get    "/pharmacies/:id",     PharmacyController,      :show
    post   "/pharmacies",         PharmacyController,      :create
  end

  defp authenticate_agent(conn, _) do
    assign(
      conn,
      :agent,
      GuardianController.identify_agent(conn) |> nilify_error())
  end
end

lib/assessment_web/controllers/order_controller.ex
defmodule AssessmentWeb.OrderController do
  use AssessmentWeb, :controller

  import AssessmentWeb.ControllerUtilities,
    only: [ authentication_error: 2,
            authorization_error: 2,
            changeset_error: 2,
            internal_error: 2,
            resource_error: 3,
            send_attachment: 4,
            validation_error: 2,
          ]
  import AssessmentWeb.GuardianController, only: [authenticate_agent: 1]
  import AssessmentWeb.OrderUtilities,
    only: [ normalize_validate_creation: 2,
            normalize_validate_index: 2,
            normalize_validate_update: 3,
          ]
  import Utilities, only: [accumulate_errors: 1]
  import AssessmentWeb.Utilities, only: [to_changeset: 2]

  alias Assessment.Accounts
  alias Assessment.Accounts.{Administrator,Courier,Pharmacy}
  alias Assessment.Orders
  alias Assessment.Orders.Order
  alias AssessmentWeb.Browser.OrderView

  plug :authenticate

  @error :error
  @new :new
  @no_resource :no_resource
  @index :index
  @info :info
  @normalized_params :normalized_params
  @not_authenticated :not_authenticated
  @not_authorized :not_authorized
  @ok :ok
  @request_path :request_path
  @show :show

  def create(conn, %{"order" => params}) do
    with {@ok, agent} <- authenticate_agent(conn),
         account <- Accounts.specify_agent(agent),
         {@ok, _} <- authorize_admin_or_pharmacy(account),
         validated_params <- normalize_validate_creation(params, account),
         {@ok, normalized_params} <- accumulate_errors(validated_params),
         {@ok, order} <- Orders.create_order(normalized_params) do
      conn
      |> put_flash(@info, "Order created successfully.")
      |> redirect(to: order_path(conn, @show, order))
    else
      {@error, @not_authenticated} ->
        conn
        |> authentication_error("Must log in to create an order")
      {@error, @not_authorized} ->
        conn
        |> authorization_error("Not authorized to create an order")
      {@error, %{errors: errors, valid_results: valid_results}} ->
        changeset =
          errors
          |> OrderView.format_upsert_errors()
          |> to_changeset(valid_results)
        conn
        |> changeset_error(%{view: "new.html", changeset: changeset})
      {@error, %Ecto.Changeset{} = changeset} ->
        conn
        |> changeset_error(%{view: "new.html", changeset: changeset})
      _ ->
        conn
        |> internal_error("ORCR_B")
    end
  end

  def csv_index(conn, params) do
    with {@ok, agent} <- authenticate_agent(conn),
         account <- Accounts.specify_agent(agent),
         validated_params <- normalize_validate_index(params, account),
         {@ok, normalized_params} <- accumulate_errors(validated_params),
         orders <- Orders.list_orders(normalized_params),
         csv <- OrderView.to_csv(orders) do
      conn
      |> send_attachment("text/csv", "orders.csv", csv)
    else
      {@error, @not_authenticated} ->
        conn
        |> authentication_error("Must log in to view orders")
      {@error, %{errors: errors, valid_results: _}} ->
        conn
        |> validation_error(OrderView.format_index_errors(errors))
      _ ->
        conn
        |> internal_error("ORIN_B")
    end
  end

  def index(conn, params) do
    with {@ok, agent} <- authenticate_agent(conn),
         account <- Accounts.specify_agent(agent),
         validated_params <- normalize_validate_index(params, account),
         {@ok, normalized_params} <- accumulate_errors(validated_params),
         orders <- Orders.list_orders(normalized_params) do
      conn
      |> assign(@normalized_params, normalized_params)
      |> render("index.html", orders: orders)
    else
      {@error, @not_authenticated} ->
        conn
        |> authentication_error("Must log in to view orders")
      {@error, %{errors: errors, valid_results: _}} ->
        conn
        |> validation_error(OrderView.format_index_errors(errors))
      _ ->
        conn
        |> internal_error("ORIN_B")
    end
  end

  def new(conn, _params) do
    with {@ok, agent} <- authenticate_agent(conn),
         account <- Accounts.specify_agent(agent),
         {@ok, _} <- authorize_admin_or_pharmacy(account) do
      conn
      |> render("new.html", changeset: Orders.change_order(%Order{}))
    else
      {@error, @not_authenticated} ->
        conn
        |> authentication_error("Must log in to create an order")
      {@error, @not_authorized} ->
        conn
        |> authorization_error("Not authorized to create an order")
      _ ->
        conn
        |> internal_error("ORNE_B")
    end
  end

  def show(conn, %{"id" => id}) do
    with {@ok, agent} <- authenticate_agent(conn),
         account <- Accounts.specify_agent(agent),
         {@ok, order} <- Orders.get_order(id),
         {@ok, _} <- authorize(account, order) do
      conn
      |> render("show.html", order: order)
    else
      {@error, @not_authenticated} ->
        conn
        |> authentication_error("Must log in to view order ##{id}")
      {@error, @no_resource} ->
        conn
        |> resource_error("order ##{id}", "does not exist")
      {@error, @not_authorized} ->
        conn
        |> authorization_error("Not authorized to view order ##{id}")
      _ ->
        conn
        |> internal_error("ORSH_B")
    end
  end

  def edit(conn, %{"id" => id}) do
    with {@ok, agent} <- authenticate_agent(conn),
         {@ok, order} <- Orders.get_order(id),
         account <- Accounts.specify_agent(agent),
         {@ok, _} <- authorize(account, order) do
      conn
      |> render("edit.html", order_id: id, changeset: Orders.change_order(order))
    else
      {@error, @not_authenticated} ->
        conn
        |> authentication_error("Must log in to update order ##{id}")
      {@error, @no_resource} ->
        conn
        |> resource_error("order ##{id}", "does not exist")
      {@error, @not_authorized} ->
        conn
        |> authorization_error("Not authorized to update order ##{id}")
      _ ->
        conn
        |> internal_error("ORED_B")
    end
  end

  def update(conn, %{"id" => id, "order" => params}) do
    with {@ok, agent} <- authenticate_agent(conn),
         {@ok, order} <- Orders.get_order(id),
         account <- Accounts.specify_agent(agent),
         {@ok, _} <- authorize(account, order),
         validated_params <- normalize_validate_update(order, params, account),
         {@ok, normalized_params} <- accumulate_errors(validated_params),
         {@ok, new_order} <- Orders.update_order(order, normalized_params) do
      conn
      |> put_flash(@info, "Order ##{id} updated successfully.")
      |> redirect(to: order_path(conn, @show, new_order))
    else
      {@error, @not_authenticated} ->
        conn
        |> authentication_error("Must log in to update order ##{id}")
      {@error, @no_resource} ->
        conn
        |> resource_error("order ##{id}", "does not exist")
      {@error, @not_authorized} ->
        conn
        |> authorization_error("Not authorized to update order ##{id}")
      {@error, %{errors: errors, valid_results: valid_results}} ->
        changeset =
          errors
          |> OrderView.format_upsert_errors()
          |> to_changeset(valid_results)
        conn
        |> changeset_error(%{
              view: "edit.html",
              changeset: changeset,
              order_id: id,
            })
      {@error, %Ecto.Changeset{} = changeset} ->
        conn
        |> changeset_error(%{
              view: "edit.html",
              changeset: changeset,
              order_id: id,
            })
      _ ->
        conn
        |> internal_error("ORCR_B")
    end
  end

  def delete(conn, %{"id" => id}) do
    with {@ok, agent} <- authenticate_agent(conn),
         account <- Accounts.specify_agent(agent),
         {@ok, order} <- Orders.get_order(id),
         {@ok, _} <- authorize(account, order),
         {@ok, _} <- Orders.delete_order(order) do
      conn
      |> put_flash(@info, "Order ##{id} deleted successfully.")
      |> redirect(to: order_path(conn, @index))
    else
      {@error, @not_authenticated} ->
        conn
        |> authentication_error("Must log in to delete order ##{id}")
      {@error, @no_resource} ->
        conn
        |> resource_error("order ##{id}", "does not exist")
      {@error, @not_authorized} ->
        conn
        |> authorization_error("Not authorized to delete order ##{id}")
      {@error, %Ecto.Changeset{}} ->
        conn
        |> put_flash(@error, "Failure to delete order ##{id}")
        |> redirect(to: order_path(conn, @show, id))
      _ ->
        conn
        |> internal_error("ORSH_B")
    end
  end

  defp authenticate(conn, _) do
    if conn.assigns.agent do
      conn
    else
      conn
      |> put_flash(@error, "You must be logged in to manage orders.")
      |> put_session(@request_path, conn.request_path)
      |> redirect(to: session_path(conn, @new))
      |> halt()
    end
  end

  defp authorize(account, order) do
    authorized? = case account do
      %Administrator{} -> true
      %Courier{} -> account.id == order.courier_id
      %Pharmacy{} -> account.id == order.pharmacy_id
    end
    if authorized? do
      {@ok, account}
    else
      {@error, @not_authorized}
    end
  end

  defp authorize_admin_or_pharmacy(account) do
    authorized? = case account do
      %Administrator{} -> true
      %Pharmacy{} -> true
      _ -> false
    end
    if authorized? do
      {@ok, account}
    else
      {@error, @not_authorized}
    end
  end
end

lib/demo_web/controllers/browser/administrator_controller.ex
defmodule DemoWeb.Browser.AdministratorController do
  use DemoWeb, :controller

  import DemoWeb.Browser.ControllerUtilities,
    only: [ id_type_validation_error: 1,
            internal_error: 2,
            match_error: 2,
            resource_error: 3,
          ]
  import DemoWeb.ControllerUtilities, only: [validate_id_type: 1]

  alias Demo.Accounts
  alias Demo.Accounts.Agent

  plug :authenticate_administrator

  @error :error
  @ignore :ignore
  @index :index
  @info :info
  @invalid_parameter :invalid_parameter
  @new :new
  @no_resource :no_resource
  @ok :ok
  @request_path :request_path
  @show :show

  def create(conn, %{"agent" => agent_params}) do
    case Accounts.create_administrator(agent_params) do
      {@ok, %Agent{administrator: administrator}} ->
        conn
        |> put_flash(@info, "Administrator created successfully.")
        |> redirect(to: administrator_path(conn, @show, administrator))
      {@error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_status(400)
        |> render("new.html", changeset: changeset)
      _ ->
        conn
        |> internal_error("ADCR-B")
    end
  end
  def create(conn, _) do
    conn
    |> match_error("to create an administrator")
  end

  def delete(conn, %{"id" => id}) do
    with {@ok, _} <- validate_id_type(id),
         {@ok, administrator} <- Accounts.get_administrator(id),
         {@ok, _} = Accounts.delete_administrator(administrator) do
      conn
      |> put_flash(@info, "Administrator deleted successfully.")
      |> redirect(to: administrator_path(conn, @index))
    else
      {@error, {@invalid_parameter, _}} ->
        conn
        |> id_type_validation_error()
      {@error, @no_resource} ->
        conn
        |> resource_error("administrator ##{id}", "does not exist")
      _ ->
        conn
        |> internal_error("ADDE-B-1")
    end
  end
  def delete(conn, _), do: conn |> internal_error("ADDE-B-2")

  def index(conn, _params) do
    conn
    |> render("index.html", administrators: Accounts.list_administrators())
  end

  def new(conn, _params) do
    conn
    |> render("new.html", changeset: Accounts.change_administrator())
  end

  def show(conn, %{"id" => id}) do
    with {@ok, _} <- validate_id_type(id),
         {@ok, administrator} <- Accounts.get_administrator(id) do
      conn
      |> render("show.html", administrator: administrator)
    else
      {@error, {@invalid_parameter, _}} ->
        conn
        |> id_type_validation_error()
      {@error, @no_resource} ->
        conn
        |> resource_error("administrator ##{id}", "does not exist")
      _ ->
        conn
        |> internal_error("ADSH-B-1")
    end
  end
  def show(conn, _), do: conn |> internal_error("ADSH-B-2")

  defp authenticate_administrator(conn, _) do
    agent = conn.assigns.agent
    if agent && agent.account_type == "administrator" do
      conn
    else
      conn
      |> put_flash(@error, "You must be logged in as an administrator to manage administrators.")
      |> put_session(@request_path, @ignore)
      |> redirect(to: session_path(conn, @new))
      |> halt()
    end
  end
end

lib/demo_web/controllers/browser/page_controller.ex
defmodule DemoWeb.Browser.PageController do
  use DemoWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/demo_web/views/browser/administrator_view.ex
defmodule DemoWeb.Browser.AdministratorView do
  use DemoWeb, :view
end

lib/demo_web/views/browser/courier_view.ex
defmodule DemoWeb.Browser.CourierView do
  use DemoWeb, :view
end

lib/demo_web/views/browser/error_view.ex
defmodule DemoWeb.Browser.ErrorView do
  use DemoWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  def render("500.html", _assigns) do
    "Internal Server Error"
  end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/demo_web/views/browser/layout_view.ex
defmodule DemoWeb.Browser.LayoutView do
  use DemoWeb, :view
end

lib/demo_web/views/browser/page_view.ex
defmodule DemoWeb.Browser.PageView do
  use DemoWeb, :view
end

lib/demo_web/views/browser/patient_view.ex
defmodule DemoWeb.Browser.PatientView do
  use DemoWeb, :view
end

lib/demo_web/views/browser/pharmacy_view.ex
defmodule DemoWeb.Browser.PharmacyView do
  use DemoWeb, :view
end

lib/demo_web/views/browser/session_view.ex
defmodule DemoWeb.Browser.SessionView do
  use DemoWeb, :view
end

lib/demo_web/templates/browser/order/edit.html.eex
<h2>Edit Order</h2>

<%= render "edit_form.html", Map.put(assigns, :action, order_path(@conn, :update, @order_id)) %>

<span><%= link "Back", to: order_path(@conn, :index) %></span>

lib/demo_web/templates/browser/order/edit_form.html.eex
<%= form_for @changeset, @action, [as: "order", method: "put"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, "patient_id", "Patient id", class: "control-label" %>
    <%= number_input f, :patient_id, class: "form-control" %>
    <%= error_tag f, :patient_id %>
  </div>

  <%= if is_pharmacy?(@agent) do %>
    <%= hidden_input f, :pharmacy_id, value: @agent.pharmacy.id, class: "form-control" %>
  <% else %>
    <div class="form-group">
      <%= label f, "pharmacy_id", "Pharmacy id", class: "control-label" %>
      <%= number_input f, :pharmacy_id, class: "form-control" %>
      <%= error_tag f, :pharmacy_id %>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, "courier_id", "Courier id", class: "control-label" %>
    <%= number_input f, :courier_id, class: "form-control" %>
    <%= error_tag f, :courier_id %>
  </div>

  <div class="form-group">
    <%= label f, "order_state", "Order state", class: "control-label" %>
    <%= text_input f, :order_state_description, class: "form-control" %>
    <%= error_tag f, :order_state %>
  </div>

  <div class="form-group">
    <%= label f, "pickup_date", "Pickup date", class: "control-label" %>
    <%= date_select f, :pickup_date, class: "form-control" %>
    <%= error_tag f, :pickup_date %>
  </div>

  <div class="form-group">
    <%= label f, "pickup_time", "Pickup time", class: "control-label" %>
    <%= time_select f, :pickup_time, class: "form-control" %>
    <%= error_tag f, :pickup_time %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/demo_web/templates/browser/order/index.html.eex
<div class="btn-group" role="group">
  <a href="<%= order_state_toggle_path(@conn) %>">
    <button type="button" class="btn btn-secondary"><%= order_state_label(@conn) %></button>
  </a>
  <a href="<%= pickup_date_toggle_path(@conn) %>">
    <button type="button" class="btn btn-secondary"><%= pickup_date_label(@conn) %></button>
  </a>
</div>

<h2>Listing <%= get_qualifier(@normalized_params) %> Orders</h2>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Patient</th>
      <th>Pharmacy</th>
      <th>Courier</th>
      <th>Order state</th>
      <th>Pickup date</th>
      <th>Pickup time</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for order <- @orders do %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.patient.name %></td>
      <td><%= order.pharmacy.name %></td>
      <td><%= order.courier.name %></td>
      <td><%= order.order_state.description %></td>
      <td><%= order.pickup_date %></td>
      <td><%= format_time(order.pickup_time) %></td>

      <td class="text-right">
        <span><%= link "Show", to: order_path(@conn, :show, order), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: order_path(@conn, :edit, order), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: order_path(@conn, :delete, order), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= unless is_courier?(@agent) do %>
  <span><%= link "New Order", to: order_path(@conn, :new) %></span>
<% end %>

<br>
<span>
  <%= link "Download CSV file", to: csv_index_path(@conn) %>
</span>

lib/demo_web/templates/browser/order/new.html.eex
<h2>New Order</h2>

<%= render "new_form.html", Map.put(assigns, :action, order_path(@conn, :create)) %>

<span><%= link "Back", to: order_path(@conn, :index) %></span>

lib/demo_web/templates/browser/order/new_form.html.eex
<%= form_for @changeset, @action, [as: "order", method: "post"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, "patient_id", "Patient id", class: "control-label" %>
    <%= number_input f, :patient_id, class: "form-control" %>
    <%= error_tag f, :patient_id %>
  </div>

  <%= if is_pharmacy?(@agent) do %>
    <%= hidden_input f, :pharmacy_id, value: @agent.pharmacy.id, class: "form-control" %>
  <% else %>
    <div class="form-group">
      <%= label f, "pharmacy_id", "Pharmacy id", class: "control-label" %>
      <%= number_input f, :pharmacy_id, class: "form-control" %>
      <%= error_tag f, :pharmacy_id %>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, "courier_id", "Courier id", class: "control-label" %>
    <%= number_input f, :courier_id, class: "form-control" %>
    <%= error_tag f, :courier_id %>
  </div>

  <div class="form-group">
    <%= label f, "pickup_date", "Pickup date", class: "control-label" %>
    <%= date_select f, :pickup_date, default: get_date_today(), class: "form-control" %>
    <%= error_tag f, :pickup_date %>
  </div>

  <div class="form-group">
    <%= label f, "pickup_time", "Pickup time", class: "control-label" %>
    <%= time_select f, :pickup_time, default: get_default_time(), class: "form-control" %>
    <%= error_tag f, :pickup_time %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/demo_web/templates/browser/order/show.html.eex
<h2>Show Order</h2>

<ul>

  <li>
    <strong>ID:</strong>
    <%= @order.id %>
  </li>

  <li>
    <strong>Patient:</strong>
    <%= @order.patient.name %>
  </li>

  <li>
    <strong>Pharmacy:</strong>
    <%= @order.pharmacy.name %>
  </li>

  <li>
    <strong>Courier:</strong>
    <%= @order.courier.name %>
  </li>

  <li>
    <strong>Order state:</strong>
    <%= @order.order_state.description %>
  </li>

  <li>
    <strong>Pickup date:</strong>
    <%= @order.pickup_date %>
  </li>

  <li>
    <strong>Pickup time:</strong>
    <%= format_time(@order.pickup_time) %>
  </li>

</ul>

<span><%= link "Edit", to: order_path(@conn, :edit, @order) %></span>
<span><%= link "Back", to: order_path(@conn, :index) %></span>